import os
from dotenv import load_dotenv

load_dotenv()

CHUNK_SIZE    = 1200
CHUNK_OVERLAP = 200

PINECONE_API_KEY    = os.getenv("PINECONE_API_KEY")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME")
PINECONE_NAMESPACE  = os.getenv("PINECONE_NAMESPACE")
PINECONE_DIMENSION  = os.getenv("PINECONE_DIMENSION")
PINECONE_METRIC     = os.getenv("PINECONE_METRIC")
PINECONE_REGION     = os.getenv("PINECONE_REGION")
PINECONE_CLOUD      = os.getenv("PINECONE_CLOUD")

DENSE_EMBEDDING_MODEL      = os.getenv("DENSE_EMBEDDING_MODEL")
DENSE_EMBEDDING_ONNX_FILE  = os.getenv("DENSE_EMBEDDING_ONNX_FILE")
SPARSE_EMBEDDING_MODEL     = os.getenv("SPARSE_EMBEDDING_MODEL")
SPARSE_EMBEDDING_ONNX_FILE = os.getenv("SPARSE_EMBEDDING_ONNX_FILE")
HYBRID_ALPHA               = float(os.getenv("HYBRID_ALPHA", 0.5))

HF_TOKEN = os.getenv("HF_TOKEN")

LANGFUSE_SECRET_KEY=os.getenv('LANGFUSE_SECRET_KEY')
LANGFUSE_PUBLIC_KEY=os.getenv('LANGFUSE_PUBLIC_KEY')
LANGFUSE_BASE_URL=os.getenv('LANGFUSE_BASE_URL')