import os
from dotenv import load_dotenv

load_dotenv()

CHUNK_SIZE    = 1200
CHUNK_OVERLAP = 200

KEY_EXTRACTION_PROMPT_NAME = 'key_extraction_prompt'

PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME")
PINECONE_NAMESPACE = os.getenv("PINECONE_NAMESPACE")
PINECONE_DIMENSION = 1024
PINECONE_METRIC = "dotproduct"
PINECONE_REGION = "us-east-1"
PINECONE_CLOUD = "aws"


EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", 'BAAI/bge-large-en-v1.5' )

HF_TOKEN = os.getenv("HF_TOKEN")

LANGFUSE_SECRET_KEY=os.getenv('LANGFUSE_SECRET_KEY')
LANGFUSE_PUBLIC_KEY=os.getenv('LANGFUSE_PUBLIC_KEY')
LANGFUSE_BASE_URL=os.getenv('LANGFUSE_BASE_URL')